# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'cc9f6b3e-07cc-4ed5-a252-710bd96ccd20'
    definition: '5'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: CmdLine@2
  inputs:
    script: |
      cd $(Pipeline.Workspace)/app1
      cat build.txt